/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bingo;

import Bingo.Engine.BingoImpl;
import Bingo.Engine.Models.Field;
import org.junit.Test;

import java.util.List;

import static org.junit.Assert.*;

public class AppTest {

    BingoImpl engine = new BingoImpl();

    // Testen, ob "isGameOver" vor Spielstart richtig funktioniert
    @Test
    public void testGameOverBeforeGameStart() {
        String msg = "The game is already over before the game starts!";
        assertFalse(msg, engine.isGameOver());
    }

    // Testen, ob die nicht gezogenen Bälle vor Spielstart voll sind
    @Test
    public void testNotDrawnBalls() {
        String msg = "The size of this list should be 75!";
        assertEquals(msg, engine.notDrawnBalls().size(), 75);
    }

    // Testen, ob die gezogenen Bälle vor Spielstart leer sind
    @Test
    public void testDrawnBalls() {
        String msg = "The size of this list should be 0!";
        assertEquals(msg, 0, engine.drawnBalls().size());
    }

    // Prüfen, ob die einzelnen Inhalte der Felder des ersten Spielers korrekt sind
    @Test
    public void checkPlayerOneCardValues() {
        String msg = "Values are wrong!";
        this.checkValues(engine.pOneCard(), msg);
    }

    // Prüfen, ob die einzelnen Inhalte der Felder des zweiten Spielers korrekt sind
    @Test
    public void checkPlayerTwoCardValues() {
        String msg = "Values are wrong!";
        this.checkValues(engine.pTwoCard(), msg);
    }

    public void checkValues(List<Field> tempList, String msg) {
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                int currValue = tempList.get((i * 5) + j).getValue();
                assertTrue(msg, currValue > (i * 15) && currValue <= (i * 15) + 15);
            }
        }
    }

    // Testen, ob die kugeln die richtigen Werte haben
    @Test
    public void checkBallsValue() {
        String msg = "Value of some balls are out of range!";
        int currValue;
        int checkValue;
        for (int i = 0; i < engine.notDrawnBalls().size(); i++) {
            checkValue = engine.notDrawnBalls().get(i);
            for (int j = 0; j < engine.notDrawnBalls().size(); j++) {
                currValue = engine.notDrawnBalls().get(j);
                assertFalse(msg,currValue < 0 || currValue > 75 );
                if (i != j) {
                    msg = "Value of some balls are equal!";
                    assertNotEquals(msg, checkValue, currValue);
                }
            }
        }
    }

    // Testen, ob der Liste der gezogenen Bälle ein Ball hinzugefügt wird, wenn man eine Kugel zieht
    @Test
    public void addBallInDrawnBalls() {
        engine.drawBall();
        String msg = "Drawn ball is not added in list of drawn balls!";
        assertEquals(msg, 1, engine.drawnBalls().size());
    }

    // Testen, ob der Liste der noch nicht gezogenen Bälle ein Ball entfernt wird, wenn man eine Kugel zieht
    @Test
    public void removeBallFromDrawnBalls() {
        engine.drawBall();
        String msg = "Drawn balls is not removed from not drawn List!";
        assertEquals(msg, 74, engine.notDrawnBalls().size());
    }

    // Testen, ob die richtige Zahl in die gezogenen Bälle abgelegt wird
    @Test
    public void checkValueOfDrawnBall() {
        String msg = "The number of the current drawn ball was not pushed correctly into the list of drawn balls!";
        int currBall = engine.drawBall();
        int inDrawnBalls = engine.drawnBalls().get(0);
        assertEquals(msg, currBall, inDrawnBalls);
    }

    // Testen, ob die richtige Zahl aus der Liste der noch nicht gezogenen Bälle entfern wird
    @Test
    public void checkValueOfNotDrawnBall() {
        String msg = "The number of the drawn ball still exist in the list of not drawn balls!";
        int currBall = engine.drawBall();
        assertFalse(msg, engine.notDrawnBalls().contains(currBall));
    }

    // Testen, ob es möglich ist, mehr als 75 Bälle zu ziehen
    @Test
    public void drawMoreBallsThenExist() {
        String msg = "It is possible to draw more then 75 balls!";
        boolean test = true;
        this.drawAllBalls();
        try {
            engine.drawBall();
        } catch (AssertionError error) {
            System.out.println(error.getMessage());
            test = false;
        }
        assertFalse(msg, test);
    }

    // Testen, ob alle Felder des ersten Spielers vor Spielstart nicht markiert sind
    @Test
    public void playerOneFieldsAreUnmarked() {
        String msg = "Fields should not be marked!";
        engine.pOneCard().forEach(field -> assertFalse(msg, field.isMarked()));
    }

    // Testen, ob alle Felder des zweiten Spielers vor Spielstart nicht markiert sind
    @Test
    public void playerTwoFieldsAreUnmarked() {
        String msg = "Fields should not be marked!";
        engine.pTwoCard().forEach(field -> assertFalse(msg, field.isMarked()));
    }

    // Testen, ob die Funktion zum markieren eines Feldes für den ersten Spieler funktioniert
    @Test
    public void checkMarkFieldPlayerOne() {
        this.drawAllBalls();
        engine.pOneMarkField(1);
        String msg = "It is not possible to mark a field!";
        assertTrue(msg, engine.pOneCard().get(1).isMarked());
    }

    // Testen, ob die Funktion zum markieren eines Feldes für den zweiten Spieler funktioniert
    @Test
    public void checkMarkFieldPlayerTwo() {
        this.drawAllBalls();
        engine.pTwoMarkField(1);
        String msg = "It is not possible to mark a field!";
        assertTrue(msg, engine.pTwoCard().get(1).isMarked());
    }

    // Testen, ob man bei der Methode zum markieren eines Feldes für den ersten Spieler einen nicht erlaubten Parameter-Wert benutzen kann
    @Test
    public void checkMarkFieldWithWrongIndexPlayerOne() {
        boolean works;
        String msg = "To mark a field with a wrong index was accepted!";
        try {
            engine.pOneMarkField(200);
            works = true;
        } catch (AssertionError e) {
            works = false;
        }
        assertFalse(msg, works);
    }

    // Testen, ob man bei der Methode zum markieren eines Feldes für den zweiten Spieler einen nicht erlaubten Parameter-Wert benutzen kann
    @Test
    public void checkMarkFieldWithWrongIndexPlayerTwo() {
        String msg = "To mark a field with a wrong index was accepted!";
        boolean works;
        try {
            engine.pTwoMarkField(200);
            works = true;
        } catch (AssertionError e) {
            works = false;
        }
        assertFalse(msg, works);
    }

    // Testen, ob die Engine den Sieg des ersten Spielers erkennt
    @Test
    public void gameOverAfterWinPlayerOne() {
        this.drawAllBalls();
        String msg = "The game should be game over!";
        engine.pOneCard().stream().limit(5).map(Field::getIndex).forEach(index -> engine.pOneMarkField(index));
        assertTrue(msg, engine.isGameOver());
    }

    // Testen, ob die Engine den Sieg des zweiten Spielers erkennt
    @Test
    public void gameOverAfterWinPlayerTwo() {
        this.drawAllBalls();
        String msg = "The game should be game over!";
        engine.pTwoCard().stream().limit(5).map(Field::getIndex).forEach(index -> engine.pTwoMarkField(index));
        assertTrue(msg, engine.isGameOver());
    }

    // Testen, ob nach "newGame()" die Liste der gezogenen Bälle zurückgesetzt wird
    @Test
    public void testNewGameDrawnBalls() {
        String msg = "Balls did no reset!";
        this.drawAllBalls();
        List<Integer> oldBallList = engine.drawnBalls();
        engine.newGame();
        List<Integer> newBallList = engine.drawnBalls();
        assertNotEquals(msg, oldBallList, newBallList);
    }

    // Testen, ob nach "newGame()" der erste Spieler eine neue Karte erhält
    @Test
    public void testNewGamePlayerOneCard() {
        String msg = "Card did no reset!";
        List<Field> oldPlayerList = engine.pOneCard();
        engine.newGame();
        List<Field> newPlayerList = engine.pOneCard();
        assertNotEquals(msg, oldPlayerList, newPlayerList);
    }

    // Testen, ob nach "newGame()" der zweite Spieler eine neue Karte erhält
    @Test
    public void testNewGamePlayerTwoCard() {
        String msg = "Card did no reset!";
        List<Field> oldPlayerTwoList = engine.pTwoCard();
        engine.newGame();
        List<Field> newPlayerTwoList = engine.pTwoCard();
        assertNotEquals(msg, oldPlayerTwoList, newPlayerTwoList);
    }

    // Testen, ob man mit einer horizontalen Reihe gewinnen kann
    @Test
    public void winConditionsHorizontal() {
        String msg = "Horizontal winning conditions do not work!";
        for (int i = 0; i < 5; i++) {
            this.drawAllBalls();
            for (int j = 0; j < 5; j++) {
                engine.pOneMarkField((j * 5) + i);
            }
            assertTrue(msg, engine.isGameOver());
            engine.newGame();
        }
    }

    // Testen, ob man mit einer vertikalen Reihe gewinnen kann
    @Test
    public void winConditionsVertical() {
        String msg = "Vertical winning conditions do not work!";
        for (int i = 0; i < 5; i++) {
            this.drawAllBalls();
            for (int j = 0; j < 5; j++) {
                engine.pOneMarkField(j + (i * 5));
            }
            assertTrue(msg, engine.isGameOver());
            engine.newGame();
        }
    }

    // Testen, ob man mit einer Diagonalen Reihe gewinnen kann
    @Test
    public void winConditionsDiagonal() {
        String msg = "Diagonal winning conditions do not work!";
        List<Integer> diaOne = List.of(0, 6, 12, 18, 24);
        List<Integer> diaTwo = List.of(4, 8, 12, 16, 20);

        this.drawAllBalls();
        diaOne.forEach(i -> engine.pOneMarkField(i));
        assertTrue(engine.isGameOver());
        engine.newGame();
        this.drawAllBalls();
        diaTwo.forEach(i -> engine.pOneMarkField(i));
        assertTrue(msg, engine.isGameOver());

    }

    // Testen, ob man die Wert der Felder einer Bingo-Karte in der Engine ändern kann
    @Test
    public void manipulateCard() {
        String msg = "Card in engine is mutable!";
        engine.newGame();
        List<Field> list = engine.pOneCard();
        this.drawAllBalls();
        list.forEach(Field::setMark);
        engine.pOneMarkField(2);
        assertFalse(msg, engine.isGameOver());
    }

    private void drawAllBalls() {
        for (int i = 0; i < 75; i++) {
            engine.drawBall();
        }
    }

}
