/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bingo;

import Bingo.Engine.Engine;
import Bingo.Engine.EngineImpl;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    @Test public void testEngine() {
        Engine engineUnderTest = new EngineImpl();
        assertNotNull("Engine should have some tests",engineUnderTest);
    }

    @Test
    public void name() {
    }
}
