/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bingo;

import Bingo.GUI.GUI;

public class App {
    public static void main(String[] args) {

         GUI.run();

    }
}
