/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bingo;

import Bingo.Representation.Representation;

public class App {
    public static void main(String[] args) {

         Representation.run();

    }
}
