/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bingo;

import Bingo.Engine.Engine;
import Bingo.Engine.EngineImpl;
import Bingo.Representation.Representation;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Representation.run(args);


       // Engine-Test
/*
        Engine test = new EngineImpl();

        for (int i = 0; i < 75; i++) {
            test.drawBall();
        }


        for (int i = 0; i < 25; i++) {
            test.markPlayerCard(i);
        }

        for (int i = 0; i < 25; i++) {
            System.out.println(test.isPlayerFieldWinner(i));
        }



        while (!test.isGameOver()) {
            test.drawBall();

            for (int i = 0; i < 25; i++) {
                test.markPlayerCard(i);
            }

                test.autoMarkCpuCard();


            System.out.println(test);
        }


         */




    }
}
